# Generated by Django 4.1.1 on 2022-11-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(default=0, upload_to='post/'),
            preserve_default=False,
        ),
    ]
