# Generated by Django 4.1.1 on 2022-11-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_blogmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='image',
        ),
    ]
